### ISSUE TITLE
em ịch hỏi ý kiến 

### ISSUE THREAD

**Issue by ducduy20** [FullStack-Swift/TodoList#2]
I'm Duy here.I've laerned the basics, then what should i learn next or just code for this basic part

**Comment by NguyenPhongVN** [comment]
Actually, I don't know. It depends on your current knowledge, but I have some suggestions for you:
UI: SwiftUI and UIKit (l prefer SwiftUI)
Architecture: Composable Architecture, Redux, Feedback Loop. (I prefer Composable Architecture):
https://www.pointfree.co/collections/composable-architecture
https://github.com/SwiftRex/SwiftRex
https://github.com/FullStack-Swift/Feedback-Loop
Function Programming and Reactive Programming: RxSwift, ReactiveSwift, Combine(l prefer Combine)
https://github.com/ReactiveX/RxSwift
https://github.com/ReactiveCocoa/ReactiveSwift
https://github.com/FullStack-Swift/SwiftExtension
data processing: SwiftyJSON ...
database: Realm, CoreData.
https://github.com/realm/realm-swift
Networking: Alamofire, Moya, or something else like Networking.https://github.com/FullStack-Swift/Networking
If you are a newbie ios developer, l think SwiftUI, Combine, Composable Architecture, Networking and  Realm is the best choice.

**Comment by ducduy20** [comment]
thank you 👍

**Comment by ducduy20** [comment]
Can you tell me how to conect with you, I'm "ịch" -neighbor.
what software do you have to chat ?????

**Comment by NguyenPhongVN** [comment]
check pm. 😌
